In [32]:

# Import NumPy as its abbreviation 'np'
import numpy as np

In [33]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2= np.array([[2,  3,  4],
              [4.5,5.6,5.5]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3],
                [6, 7, 9],
                [2, 3, 2]],
              
                [[4, 8, 9],
                [9, 9, 9],
                [4, 5, 9]]])

a1

array([1, 2, 3])

In [35]:
a2

array([[2. , 3. , 4. ],
       [4.5, 5.6, 5.5]])

In [34]:
a3

array([[[1, 2, 3],
        [6, 7, 9],
        [2, 3, 2]],

       [[4, 8, 9],
        [9, 9, 9],
        [4, 5, 9]]])

In [9]:
a1.dtype, a1.size, type(a1), a1.shape

(dtype('int32'), 3, numpy.ndarray, (3,))

In [10]:
a2.shape, a2.size, a2.dtype, type(a2)

((2, 3), 6, dtype('float64'), numpy.ndarray)

In [11]:
a3.shape, a3.size, a3.dtype, type(a3)

((2, 3, 3), 18, dtype('int32'), numpy.ndarray)

In [14]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2, columns = ["Column1", "column2", "column3"], index = ["row1", "row2"])
df

Column1  column2  column3
row1      2.0      3.0      4.0
row2      4.5      5.6      5.5

In [18]:
# Create an array of shape (10, 2) with only ones
ones = np.ones([10,2])
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros([7,2,3])
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
import numpy as np
range_array = np.arange(0,100,3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [14]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array1 = np.random.randint(10, size = (7,2))
random_array1

array([[6, 0],
       [2, 4],
       [5, 0],
       [6, 0],
       [6, 6],
       [9, 5],
       [1, 6]])

In [17]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array2 = np.random.random(size = (3,5))
random_array2

array([[0.27887551, 0.77768323, 0.35387459, 0.47355563, 0.6071754 ],
       [0.54807356, 0.36164482, 0.48796247, 0.4701377 , 0.07536663],
       [0.44796845, 0.81081118, 0.7909355 , 0.60827884, 0.26854172]])

In [25]:
# Set the random seed to 42


# Create a random array of numbers between 0 & 10 of size (4, 6)

np.random.seed(42)
random_array3 = np.random.randint(10, size= (4,6))
random_array3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [26]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable


# Find the unique numbers in the array you just created
random_array4 = np.random.randint(10, size = (3,7))
random_array4

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6],
       [1, 3, 8, 1, 9, 8, 9]])

In [28]:
np.unique(random_array4)

array([0, 1, 2, 3, 4, 6, 8, 9])

In [29]:
# Find the 0'th index of the latest array you created
random_array4[0]

array([8, 0, 9, 2, 6, 3, 8])

In [30]:
# Get the first 2 rows of latest array you created
random_array4[:2]

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]])

In [36]:
a3

array([[[1, 2, 3],
        [6, 7, 9],
        [2, 3, 2]],

       [[4, 8, 9],
        [9, 9, 9],
        [4, 5, 9]]])

In [39]:
a3[:, :, :2]

array([[[1, 2],
        [6, 7],
        [2, 3]],

       [[4, 8],
        [9, 9],
        [4, 5]]])

In [43]:
# Get the first 2 values of the first 2 rows of the latest array
a3[:1, :3, :2]

array([[[1, 2],
        [6, 7],
        [2, 3]]])

In [53]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

r1 = np.random.randint(10, size = (3,5))
r1

array([[1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1],
       [9, 1, 9, 3, 7]])

In [52]:
r2= np.ones([3,5])
r2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
r1+r2


ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [54]:
r1+r2

array([[ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.],
       [10.,  2., 10.,  4.,  8.]])